### ISSUE TITLE
Config customization not working correctly

### ISSUE THREAD

**Issue by Cephelo** [hellozyemlya/cool-resource-finder#2] opened 2024-08-15 05:08 UTC
Tried using this config, but to no avail - Resource Scanner bugs out and points in seemingly random directions, and does not allow input of any of the custom items such as magnetite.
Config: [cool-resource-finder-registry.json](https://github.com/user-attachments/files/16621678/cool-resource-finder-registry.json)

I know the json is valid, the only thing I can think of is that the config file isn't meant for this many entries - or it's not meant for custom groups, not sure.  Any ideas?

**Comment by Cephelo** [comment] 2024-08-23 00:40
From further testing, it seems these are the issues at hand:
- Adding modded target blocks to a group causes the Resource Scanner to not work for that group: It instead points to the player's block position, and updates when it changes, but it definitely doesn't point to any target blocks.  Adding blocks from Minecraft does not cause this.
- Crafting table does not accept modded recharge items, only those from Minecraft itself
- Custom groups must be in the minecraft namespace to work, otherwise the game will crash.  (Example: `spelunkery:raw_magnetite`)  Attempting to launch the game after removing a custom group, while having/holding a scanner with that removed group registered, the same crash occurs.

Other than that, the config works fine, but these issue but a larger dampener on those who want to configure it for large modpacks.  Let me know if there's any way I can help.

**Comment by hellozyemlya** [comment] 2024-09-04 16:37
@Cephelo many thanks for report. Is that happens with any mod or with some particular? It will be great to get some minimal list of mods where it breaks.

ps: suspect that is due to load order of mods, maybe resources of third-party mods not ready yet. Will try to reproduce on my own with some random mod.

**Comment by hellozyemlya** [comment] 2024-09-04 16:39
Ah, that is https://www.curseforge.com/minecraft/mc-mods/spelunkery, will check your config. Sorry for releasing buggy mod :)

**Comment by hellozyemlya** [comment] 2024-09-05 08:01
@Cephelo can you try please updated version [0.1.2](https://modrinth.com/mod/cool-resource-finder/version/0.1.2)? I reproduced every issue(maybe except crash), problem was with loading order. Now mod will validate if block or item is found or not and it will try parse config in lazy manner, when all mods already pre-populated its blocks. Config for madnetite works fine now(at least in my setup).

ps: it was pointing not to player, but to air, that is default behaviour for items registry, when block not found - return air block xD

**Comment by hellozyemlya** [comment] 2024-09-14 19:19
Fixed in latest versions.

**Closed as completed by hellozyemlya** 2024-09-14 19:19 UTC
